# Generated by Django 4.2.3 on 2023-08-02 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200522_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 20, 10, 35, 679823, tzinfo=datetime.timezone.utc)),
        ),
    ]
